### ISSUE TITLE
newbee question: how to run outside of flywheel universe?

### ISSUE THREAD

**Issue by yarikoptic** [flywheel-apps/all-subject-bids-fmriprep#3]
would you be so kind to point us to the documentation or example run on how to (ab)use this magical flywheel gear locally without flywheel platform? our blind attempt failed:

```
yoh@typhon:~$ docker run -it --rm flywheel/all-subject-bids-fmriprep:1.0.2
Traceback (most recent call last):
  File "/flywheel/v0/run.py", line 67, in <module>
    if gtk_context.config["gear-log-level"] == "INFO":
KeyError: 'gear-log-level'
```

**Comment by AndysWorth** [comment]
Hi Yarik,

It does not make sense to run this gear outside of Flywheel because what it does is run jobs on Flywheel.

But if you're asking how to do this in general, the Flywheel CLI command `fw gear local` provides an easy way to run a gear locally.  It sets up the necessary `config.json` and `input/` and `output/` directories.  You would have to set up those things yourself and then mount them in the docker container if you wan to run a gear using a single Docker command.

If you wan to easily run jobs on Flywheel, [copy-job.py](https://gitlab.com/flywheel-io/public/flywheel-tutorials/-/tree/master/copy-job) is the way to do it.

Andy.

**Comment by yarikoptic** [comment]
Thank you! I will dig deeper later on
